### ISSUE TITLE
[Bug] Multiple GPU training not working (VITS ljspeech)

### ISSUE THREAD

**Issue by andreibezborodov** [coqui-ai/TTS#1477]
## 🐛 Description

Hello! I am trying to train a VITS model on LJSpeech using _train_vits.py_ file from _recipes/ljspeech_ on multiple GPU. Running command `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python3 TTS/bin/distribute.py --script recipes/ljspeech/vits_tts/train_vits.py` results in 8 times output of the same information about confing and begining of training. After slow training of first epoch nothing is happenning. 

### To Reproduce
**Input** `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python3 TTS/bin/distribute.py --script recipes/ljspeech/vits_tts/train_vits.py`

**Output:** 

```
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=0']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=1']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=2']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=3']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=4']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=5']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=6']
['recipes/ljspeech/vits_tts/train_vits.py', '--continue_path=', '--restore_path=', '--group_id=group_2022_04_07-150620', '--use_ddp=true', '--rank=7']

 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/a_bezborodov/LJSpeech/LJSpeech-1.1
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
 > Using CUDA: True
 > Number of GPUs: 8
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")

 > Model has 83059180 parameters

 > Model has 83059180 parameters

 > Model has 83059180 parameters

 > Model has 83059180 parameters

 > Model has 83059180 parameters
 > Model has 83059180 parameters


 > Model has 83059180 parameters

 > Model has 83059180 parameters

 > EPOCH: 0/1000
 > EPOCH: 0/1000
 > EPOCH: 0/1000
 > EPOCH: 0/1000
 > EPOCH: 0/1000
 > EPOCH: 0/1000
 > EPOCH: 0/1000

 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a

 > EPOCH: 0/1000 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a
 --> /home/a_bezborodov/LJSpeech/LJSpeech-1.1/vits_ljspeech-April-07-2022_03+06PM-0cf3265a

> DataLoader initialization
| > Tokenizer:
        | > add_blank: True
        | > use_eos_bos: False
> DataLoader initialization
        | > use_phonemes: True
| > Tokenizer:
        | > phonemizer:

        | > add_blank: True
                | > phoneme language: en-us
> DataLoader initialization
> DataLoader initialization
> DataLoader initialization
        | > use_eos_bos: False
                | > phoneme backend: gruut
| > Tokenizer:
| > Tokenizer:
| > Tokenizer:
> DataLoader initialization
| > Tokenizer:
        | > use_phonemes: True
| > Number of instances : 12969
        | > add_blank: True
        | > add_blank: True
        | > add_blank: True
> DataLoader initialization
        | > phonemizer:
        | > add_blank: True
        | > use_eos_bos: False
> DataLoader initialization
        | > use_eos_bos: False
        | > use_eos_bos: False
| > Tokenizer:
                | > phoneme language: en-us
        | > use_eos_bos: False
        | > use_phonemes: True
| > Tokenizer:
        | > use_phonemes: True
        | > use_phonemes: True
        | > add_blank: True
                | > phoneme backend: gruut
        | > use_phonemes: True
        | > phonemizer:
        | > phonemizer:
        | > add_blank: True
        | > phonemizer:
        | > use_eos_bos: False
| > Number of instances : 12969
                | > phoneme language: en-us
        | > phonemizer:
                | > phoneme language: en-us
        | > use_eos_bos: False
                | > phoneme language: en-us
        | > use_phonemes: True
                | > phoneme backend: gruut
                | > phoneme language: en-us
                | > phoneme backend: gruut
        | > use_phonemes: True
                | > phoneme backend: gruut
        | > phonemizer:
| > Number of instances : 12969
                | > phoneme backend: gruut
| > Number of instances : 12969
        | > phonemizer:
| > Number of instances : 12969
                | > phoneme language: en-us
| > Number of instances : 12969
                | > phoneme backend: gruut
                | > phoneme language: en-us
| > Number of instances : 12969
                | > phoneme backend: gruut
| > Number of instances : 12969
 | > Preprocessing samples
 | > Preprocessing samples
 | > Preprocessing samples
 | > Preprocessing samples
 | > Preprocessing samples
 | > Max text length: 188
 | > Max text length: 188
 | > Max text length: 188
 | > Max text length: 188
 | > Min text length: 13
 | > Max text length: 188
 | > Min text length: 13
 | > Min text length: 13
 | > Min text length: 13
 | > Avg text length: 100.90014650319993
 |
 | > Preprocessing samples
 | > Min text length: 13
 | > Preprocessing samples
 | > Avg text length: 100.90014650319993
 |
 | > Avg text length: 100.90014650319993
 |
 | > Max audio length: 222643.0
 | > Avg text length: 100.90014650319993
 |
 | > Max audio length: 222643.0
 | > Max audio length: 222643.0
 | > Min audio length: 24499.0
 | > Max text length: 188
 | > Max audio length: 222643.0
 | > Avg text length: 100.90014650319993
 |
 | > Max text length: 188
 | > Min audio length: 24499.0
 | > Min audio length: 24499.0
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Min audio length: 24499.0
 | > Max audio length: 222643.0
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Min text length: 13
 | > Preprocessing samples
 | > Min text length: 13
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Min audio length: 24499.0
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Avg text length: 100.90014650319993
 |
 | > Max text length: 188
 | > Avg text length: 100.90014650319993
 |
 | > Max audio length: 222643.0
 | > Max audio length: 222643.0
 | > Min audio length: 24499.0
 | > Min text length: 13
 | > Min audio length: 24499.0
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Avg text length: 100.90014650319993
 |

 > TRAINING (2022-04-07 15:06:51)
 | > Max audio length: 222643.0
 > TRAINING (2022-04-07 15:06:51)
 > TRAINING (2022-04-07 15:06:51)
 | > Min audio length: 24499.0

 > TRAINING (2022-04-07 15:06:51)
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.

 > TRAINING (2022-04-07 15:06:51)
 > TRAINING (2022-04-07 15:06:51)
 > TRAINING (2022-04-07 15:06:51)
 > TRAINING (2022-04-07 15:06:51)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.94945  (176.94945)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.91026  (101.91026)
     | > loss_duration: 1.80240  (1.80240)
     | > loss_1: 287.00562  (287.00562)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 7.48160  (7.48156)
     | > loader_time: 0.11870  (0.11868)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.94945  (176.94945)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.90982  (101.90982)
     | > loss_duration: 1.80240  (1.80240)
     | > loss_1: 287.00516  (287.00516)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 7.47180  (7.47182)
     | > loader_time: 0.13200  (0.13200)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.95003  (176.95003)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.90942  (101.90942)
     | > loss_duration: 1.80084  (1.80084)
     | > loss_1: 287.00378  (287.00378)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 7.67590  (7.67594)
     | > loader_time: 0.12330  (0.12333)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.94945  (176.94945)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.91161  (101.91161)
     | > loss_duration: 1.80240  (1.80240)
     | > loss_1: 287.00696  (287.00696)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 7.65900  (7.65902)
     | > loader_time: 0.13790  (0.13785)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.94945  (176.94945)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.91114  (101.91114)
     | > loss_duration: 1.80240  (1.80240)
     | > loss_1: 287.00650  (287.00650)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 8.09670  (8.09672)
     | > loader_time: 0.15550  (0.15548)


   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.95003  (176.95003)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.90935  (101.90935)
     | > loss_duration: 1.80084  (1.80084)
     | > loss_1: 287.00372  (287.00372)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 8.46760  (8.46759)
     | > loader_time: 0.14920  (0.14922)



   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.94945  (176.94945)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.91024  (101.91024)
     | > loss_duration: 1.80240  (1.80240)
     | > loss_1: 287.00558  (287.00558)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 8.47320  (8.47317)
     | > loader_time: 0.14600  (0.14602)
   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > loss_disc: 5.96543  (5.96543)
     | > loss_disc_real_0: 0.99829  (0.99829)
     | > loss_disc_real_1: 1.00352  (1.00352)
     | > loss_disc_real_2: 0.98388  (0.98388)
     | > loss_disc_real_3: 0.97055  (0.97055)
     | > loss_disc_real_4: 1.02909  (1.02909)
     | > loss_disc_real_5: 0.97949  (0.97949)
     | > loss_0: 5.96543  (5.96543)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.96660  (5.96660)
     | > loss_kl: 176.95003  (176.95003)
     | > loss_feat: 0.37689  (0.37689)
     | > loss_mel: 101.90838  (101.90838)
     | > loss_duration: 1.80084  (1.80084)
     | > loss_1: 287.00275  (287.00275)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020
     | > current_lr_1: 0.00020
     | > step_time: 8.48370  (8.48372)
     | > loader_time: 0.13450  (0.13455)
```
After that one epoch is slowly training (I think it should be faster on 8 A100 GPU) and nothing is hapenning - evaluation step is not beginning. There is a feeling that the whole training takes place on each of the GPU separately, so the output of everything is duplicated. 

### Expected behavior
Normal start of multi GPU training.

### Environment
```
{
    "CUDA": {
        "GPU": [
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB",
            "A100-SXM4-40GB"
        ],
        "available": true,
        "version": "11.0"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.7.1+cu110",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020"
    }
}
```
Tried some changes for distributed backend, but it does not seem to work. How can I fix that? Also attaching my config (did not change any parameters in recipes train file).

Thank you in advance!
[config.txt](https://github.com/coqui-ai/TTS/files/8442738/config.txt)

**Comment by erogol** [comment]
Thanks for posting the issue. I'll take a look.

**Comment by erogol** [comment]
It should now work if you update the 👟

```
pip install -U trainer
```

**Comment by andreibezborodov** [comment]
> It should now work if you update the 👟
> 
> ```
> pip install -U trainer
> ```

Updated the 👟via command, however it seems that the problem is still remaining.  Config information still gets dublicated like shown earlier and than I even run into a CUDA out of memory error on the first epoch (did not increase the batch size, using a training file from _recipices/_). 
Running it all with `python3 distribute.py --script train_vits_ljspeech.py --gpus "0,1,2,3,4,5,6,7"`. Tried to use `distibute.py` from 👟 package, but that does not help (previously used  `distibute.py` file from _TTS/bin/_)

![image](https://user-images.githubusercontent.com/23527206/163173216-0a3883e8-fbee-44ca-a094-8b71dd678b87.png)

**Comment by erogol** [comment]
It is now a different problem and your VRAM is not sufficient.

Try some of these:
- Reduce batch size
- Enable Mixed precision training by setting "mixed_precision=true" in the config. 
- Set min_audio_len to something smaller

So I close this as the original problem is apparently solved.
