### ISSUE TITLE
[Bug] Importing TTS overrides root logger level to `WARNING`

### ISSUE THREAD

**Issue by loukylor** [coqui-ai/TTS#2833]
### Describe the bug

Importing the TTS api will override any existing logging level to `WARNING`.

### To Reproduce

```py
import logging
logging.basicConfig(level=logging.INFO)
logging.info("Prints") # INFO:root:Prints

from TTS.api import TTS

logging.info("Doesn't print")
logging.warning("Prints") # Prints
logging.getLevelName(logging.getLogger().level) # WARNING
```

### Expected behavior

`logging.info` should continue to print logs.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.16.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

**Comment by akx** [comment]
As of fead04f779c26b6bc99a608542ecea8d39f0fbc7, your example prints

```
INFO:root:Prints
INFO:root:Doesn't print
WARNING:root:Prints
```
so I suspect this has been fixed.

**Comment by loukylor** [comment]
I just tested with the latest commit on the original machine I reported in this issue and another machine and both still have the issue. After doing this, I decided to dig further into the issue and found that [this is the line at fault](https://github.com/numpy/numpy/blob/main/numpy/distutils/log.py#L89). It appears to not be an issue with TTS, but with numpy. 

The full callstack is extremely long, but in essence, TTS imports `scipy.signal` which eventually imports `numpy.testing` which imports `numpy.distutils.ccompiler` which then imports `numpy.distutils.log` and the root logger level becomes overridden. 

It is curious that you didn't face the same issue as I did. Perhaps its an OS dependent issue or some version differences with numpy or scipy. Whatever the case, it isn't TTS's fault so I'll close the issue.
